configuration:
  itemName: "2&l[!] &aSell Wand"
  itemLore:
    - "&r"
    - "&aUses: &f&nInfinite"
    - "&r"
    - "&aRight-Click a &f&nChest &ato sell"
    - "&aeverything within it."
  sellCommand: "sellall"
  giveOtherPermission: sellwands.give.other
  selfGivePermission: sellwands.give
  pluginReloadPermission: sellwands.reload
messages:
  tooFewArguments: "&4&l[!] &cUsage: SellWands &f&n<Arg>"
  tooMuchArguments: "&4&l[!] &cUsage: SellWands &f&n<Arg>"
  incorrectTarget: "&4&l[!] &cThe player &f&n%player% &cis not online."
  missingPermission: "&4&l[!] &cYou are missing a &f&npermission-node&c."
  successfullySelfGive: "&2&l[!] &aYou have successfully given &f&nyourself &aa &f&nSellWand&a!"
  successfullyGiveTo: "&2&l[!] &aYou have successfully given &f&n%player% &aa &f&nSellWand&a!"
  pluginEnabled: "&2&l[!] &aHypeSellWands enabled, forked by &f&nPorkSkulls"
  pluginDisabled: "&2&l[!] &aHypeSellWands disabled, forked by &f&nPorkSkulls"
