author: SyFizz_
version: 0.0.1
main: fr.syfizz.hypesellwands.Main
name: HypeSellWands
description: Simple SellWands plugin.
commands:
  sellwands:
    usage: /sellwands <give|reload> [player]
    description: Allows you to give a wand to a player or to yourself
